### ISSUE TITLE
Request for knife openstack stack ...

### ISSUE THREAD

**Issue by ianrossi** [chef/knife-openstack#183]
I'm not sure if this is the right place for this request, but it would be great to have a command like this if only to be able to delete stacks so that the corresponding Chef nodes can be deleted. The `knife openstack server delete --purge` command is great for deleting individual servers, but it would be totally awesome if you could do a `knife openstack stack delete --purge [STACKNAME]` so the stack would be deleted AND all of the Chef nodes that made up the stack.

**Comment by jjasghar** [comment]
This is pretty neat, but "stacks" are specific to Heat. Heat isn't one of the "core" projects which is out of the scope of `knife openstack`.

If you need to do this, you might want to look into [chef-provisioning-fog](https://github.com/chef/chef-provisioning-fog) or write some [fog](https://github.com/fog/fog/blob/master/lib/fog/openstack/docs/orchestration.md) scripts to get around this.

Granted, if someone wrote this I'd be interested to merge it in, but I don't have the bandwidth to make it happen now.

I'm going to close this now because it's out of scope.

**Comment by ianrossi** [comment]
Thanks @jjasghar for considering and thanks for the pointers to chef-provisioning-fog. I'll take a look.
